######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 29 20:18:17 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h figure.h mainwindow.h
SOURCES += dialog.cpp figure.cpp main.cpp mainwindow.cpp
