######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 18 16:56:58 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += figure.h mainwindow.h
SOURCES += figure.cpp main.cpp mainwindow.cpp
